import { useState } from 'react';
import { GoogleGenAI } from '@google/genai';

// React explanation document: https://docs.google.com/document/d/11dvZxehChDA__k-fEg-D1HaavPbGtUY_FyCieLcnD0Y/edit?tab=t.0

// Initialize the Google Gen AI SDK using the key from the .env file
  // Note: Vite uses import.meta.env instead of process.env for environment variables
const ai = new GoogleGenAI({ apiKey: import.meta.env.VITE_GEMINI_API_KEY });

function App() {
  // NOTE: For explanation on useState and how it works (specifically how values are stored and modified), check Google doc
  const [recipeText, setRecipeText] = useState("");
    // useState hook holds the recipe text data
    // 'recipeText' is the current value, 'setRecipeText' is the function to update it

  const [parsedRecipe, setParsedRecipe] = useState(null);
    // useState hook holds the JSON object generated by Gemini from the recipe text data

  const [isLoading, setIsLoading] = useState(false);
    // useState hook holds boolean that tells us to disable button while we wait for the API connection

  // Arrow function (equivalent to lambdas in Python), called an anonymous function because it has no name --> handleParse
  // variable stores the function itself (executable instructions), NOT the return value
    // Would have to execute the function and assign it to a variable to get return value
    // Python lambda equivalent: handleParse = lambda: print("Sending to AI")
  // function even though handleParse holds the return value
  const handleParse = async () => {
    console.log("Sending to AI:", recipeText);
      // Right click inspect and check console to check log

    // Edge case: Prematurely return if recipeText (text box) is "" (empty)
    if (!recipeText.trim()) {return};
    
    setIsLoading(true); // Turn on the loading state while we call the API
    
    try {
      // API call to Gemini
      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash', 
        contents: `Extract the recipe details from the following text:\n${recipeText}`,
        config: {
          systemInstruction: "You are strictly a recipe parsing agent. You must return exactly a JSON object with three keys: 'title' (a string), 'ingredients' (an array of strings), and 'steps' (an array of strings). Do not include any conversational text.",
          responseMimeType: "application/json", 
        }
      });

      const data = JSON.parse(response.text); // Parse string into a JSON object

      setParsedRecipe(data); // Save the JSON object to parsedRecipe

    } catch (error) {
      console.error("Failed to parse recipe:", error);
      alert("Something went wrong with the AI, check the console.");
    } finally {
      setIsLoading(false); // Turn off loading state regardless of success/fail
    }
  };

  return (
    <div style={{ padding: '20px', fontFamily: 'sans-serif' }}>
      <h1>Voice-Activated Cookbook</h1>
      
      <div>
        <h2>1. Paste Your Recipe</h2>
        <textarea 
          rows="10" 
          cols="50" 
          placeholder="Paste plain text recipe here..."
          value={recipeText}
            // Dictates what text box displays, reflecting whatever value recipeText has
          onChange={(e) => setRecipeText(e.target.value)}
            // Waits for event e (every time you type a new character) to call setRecipeText to save target.value into recipeText
            // Essentially updates recipeText in realtime
        />
        <br />
        <button 
          onClick={handleParse} 
          disabled={isLoading}
          style={{ marginTop: '10px', cursor: isLoading ? 'wait' : 'pointer' }}
        >
          {/* Display 'Parsing with AI...' if isLoading=True or 'Parse Recipe with AI' if isLoading=False in the button */}
          {isLoading ? "Parsing with AI..." : "Parse Recipe with AI"}
        </button>
      </div>

      <hr style={{ margin: '20px 0' }} />

      <div>
        <h2>2. Parsed Data</h2>
        
        {/* Only show the recipe if parsedRecipe is NOT null */}
        {parsedRecipe ? (
          <div>
            <h3>{parsedRecipe.title}</h3>
            
            <h4>Ingredients:</h4>
            {/* <ul> for unordered list -- ingredients don't need to be ordered */}
            <ul>
              {/* .map() loops over the array to create an <li> (list item) for each ingredient */}
              {parsedRecipe.ingredients.map((ingredient, index) => (
                <li key={index}>{ingredient}</li>
              ))}
            </ul>

            <h4>Steps:</h4>
            {/* <ol> for ordered list -- steps have to be ordered */}
            <ol>
              {/* .map() loops over the array to create an <li> (list item) for each step */}
              {parsedRecipe.steps.map((step, index) => (
                <li key={index}>{step}</li>
              ))}
            </ol>
          </div>
        ) : (
          <p style={{ color: 'gray' }}>Waiting for recipe input...</p>
        )}
      </div>
    </div>
  )
}

export default App;