import { useState, useRef } from 'react';
import { GoogleGenAI } from '@google/genai';

// React explanation document: https://docs.google.com/document/d/11dvZxehChDA__k-fEg-D1HaavPbGtUY_FyCieLcnD0Y/edit?tab=t.0

// Initialize the Google Gen AI SDK using the key from the .env file
  // Note: Vite uses import.meta.env instead of process.env for environment variables
const ai = new GoogleGenAI({ apiKey: import.meta.env.VITE_GEMINI_API_KEY });

function App() {
  // NOTE: For explanation on useState and how it works (specifically how values are stored and modified), check Google doc
  const [recipeText, setRecipeText] = useState("");
    // useState hook holds the recipe text data; 'recipeText' is the current value, 'setRecipeText' is the function to update it

  const [parsedRecipe, setParsedRecipe] = useState(null);
    // useState hook holds the JSON object generated by Gemini from the recipe text data

  const [isLoading, setIsLoading] = useState(false);
    // useState hook holds boolean that tells us to disable button while we wait for the API connection

  const [heardCommand, setHeardCommand] = useState("");
    // useState hook holds string that tells us if microphone has received voice input

  const recognitionRef = useRef(null);
    // useRef creates persistent reference to microphone to prevent multiple listeners

  // Replaced arrow async function with standard async function
  async function handleParse() {
    if (!recipeText.trim()) {return}; // Edge case: Prematurely return if recipeText (text box) is "" (empty)
    setIsLoading(true); // Turn on the loading state while we call the API
    
    try {
      // API call to Gemini
      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash', 
        contents: `Extract the recipe details from the following text:\n${recipeText}`,
        config: {
          systemInstruction: "You are strictly a recipe parsing agent. You must return exactly a JSON object with three keys: 'title' (a string), 'ingredients' (an array of strings), and 'steps' (an array of strings). Do not include any conversational text.",
          responseMimeType: "application/json", 
        }
      });

      const data = JSON.parse(response.text); // Parse string into a JSON object
      setParsedRecipe(data); // Save the JSON object to parsedRecipe

    } catch (error) {
      console.error("Failed to parse recipe:", error);
      alert("Something went wrong with the AI, check the console.");
    } finally {
      setIsLoading(false); // Turn off loading state regardless of success/fail
    }
  };

  function textToSpeech(textToSpeak) {
    // First check that the browser supports speech synthesis
    if ('speechSynthesis' in window) {
      window.speechSynthesis.cancel(); // Stop any playing audio
      const utterance = new SpeechSynthesisUtterance(textToSpeak);
      window.speechSynthesis.speak(utterance);
    } else {
      alert("Your browser does not support text-to-speech.")
    }
  }

  function speechToText() {
    const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition; // Check for different API names for speech recognition depending on browser

    if (!SpeechRecognition) {
      alert("Your browser does not support speech recognition.");
      return;
    }

    // Initialize listening session
    const speechRecognition = new SpeechRecognition();
    speechRecognition.continuous = false; // Terminate listening session whenever user finishes speaking
    speechRecognition.lang = "en-US";

    // Once speech has been successfully captured...
    speechRecognition.onresult = function(event) {
      const transcript = event.results[0][0].transcript;
      setHeardCommand(transcript); // Display what was heard to the UI
      console.log("Microphone heard:", transcript);
    }

    // If there was an error capturing speech...
    speechRecognition.onerror = function(event) {
      console.error("Speech recognition error:", event.error);
    }

    speechRecognition.start(); // Start the microphone
    recognitionRef.current = speechRecognition; // Save current instance of speechRecognition to the reference
  }

  return (
    <div style={{ padding: '20px', fontFamily: 'sans-serif' }}>
      <h1>Voice-Activated Cookbook</h1>
      
      <div>
        <h2>1. Paste Your Recipe</h2>
        <textarea 
          rows="10" 
          cols="50" 
          placeholder="Paste plain text recipe here..."
          value={recipeText}
            // Dictates what text box displays, reflecting whatever value recipeText has
          onChange={(e) => setRecipeText(e.target.value)}
            // Waits for event e (every time you type a new character) to call setRecipeText to save target.value into recipeText
            // Essentially updates recipeText in realtime
        />
        <br />
        <button 
          onClick={handleParse} 
          disabled={isLoading}
          style={{ marginTop: '10px', cursor: isLoading ? 'wait' : 'pointer' }}
        >
          {/* Display 'Parsing with AI...' if isLoading=True or 'Parse Recipe with AI' if isLoading=False in the button */}
          {isLoading ? "Parsing with AI..." : "Parse Recipe with AI"}
        </button>
      </div>

      <hr style={{ margin: '20px 0' }} />

      <div>
        <h2>2. Parsed Data</h2>
        
        {/* Only show the recipe if parsedRecipe is NOT null */}
        {parsedRecipe ? (
          <div>
            <h3>{parsedRecipe.title}</h3>
            
            <h4>Ingredients:</h4>
            {/* <ul> for unordered list -- ingredients don't need to be ordered */}
            <ul>
              {/* .map() loops over the array to create an <li> (list item) for each ingredient */}
              {parsedRecipe.ingredients.map((ingredient, index) => (
                <li key={index}>{ingredient}</li>
              ))}
            </ul>

            <h4>Steps:</h4>
            {/* <ol> for ordered list -- steps have to be ordered */}
            <ol>
              {/* .map() loops over the array to create an <li> (list item) for each step */}
              {parsedRecipe.steps.map((step, index) => (
                <li key={index}>{step}</li>
              ))}
            </ol>
          </div>
        ) : (
          <p style={{ color: 'gray' }}>Waiting for recipe input...</p>
        )}
      </div>

      <hr style={{ margin: '20px 0' }} />

      {/* Testing the microphone and speaker */}
      <div>
        <h2>3. Voice Control Test</h2>
        
        {/* Test the Microphone */}
        <button onClick={speechToText} style={{ marginRight: '10px', padding: '8px' }}>
          🎙️ Click to Speak
        </button>
        
        {/* Test the Speaker */}
        <button 
          onClick={function() { textToSpeech("Testing text to speech.") }}
          style={{ padding: '8px' }}
        >
          🔊 Test Speaker
        </button>

        <p><strong>You said:</strong> {heardCommand || "(Nothing yet)"}</p>
      </div>
    </div>
  )
}

export default App;